/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e0e3e5',
        'surface-container-high': '#e6e8ea',
        'background': '#f7f9fb',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'outline-variant': '#bfc9bd',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#bcc7de',
        'secondary-fixed': '#d8e3fb',
        'outline': '#707a6f',
        'on-tertiary-fixed': '#0d1c2e',
        'surface': '#f7f9fb',
        'on-background': '#191c1e',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#3a485b',
        'tertiary-container': '#4b596d',
        'surface-dim': '#d8dadc',
        'on-primary-container': '#93e0a2',
        'primary': '#004c22',
        'tertiary-fixed': '#d5e3fc',
        'tertiary': '#344255',
        'secondary': '#545f73',
        'secondary-container': '#d5e0f8',
        'surface-container': '#eceef0',
        'surface-variant': '#e0e3e5',
        'tertiary-fixed-dim': '#b9c7df',
        'on-secondary-fixed': '#111c2d',
        'surface-container-low': '#f2f4f6',
        'inverse-surface': '#2d3133',
        'on-primary-fixed-variant': '#005226',
        'surface-tint': '#1f6c3a',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#191c1e',
        'surface-bright': '#f7f9fb',
        'on-secondary-fixed-variant': '#3c475a',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#8bd79b',
        'on-tertiary-container': '#c1d0e8',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#00210b',
        'primary-container': '#166534',
        'primary-fixed-dim': '#8bd79b',
        'on-secondary-container': '#586377',
        'on-surface-variant': '#404940',
        'primary-fixed': '#a6f4b5',
        'error': '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-8': '2rem',
        'container-max': '1280px',
        'space-6': '1.5rem',
        'margin-mobile': '1rem',
        'unit': '4px',
        'space-4': '1rem',
        'margin-desktop': '2.5rem',
        'space-1': '0.25rem',
        'space-2': '0.5rem',
        'space-3': '0.75rem',
        'gutter': '1rem',
      },
      fontFamily: {
        display: ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
